config/routes.rb
Rails.application.routes.draw do
  resources :productos
  resources :venta

   root 'venta#index'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :vetum
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
	has_many :productos 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:cod, :Nombre_Producto, :Costo, :stock)
    end
end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  before_action :set_ventum, only: [:show, :edit, :update, :destroy]

  # GET /venta
  # GET /venta.json
  def index
    @venta = Ventum.all
  end

  # GET /venta/1
  # GET /venta/1.json
  def show
  end

  # GET /venta/new
  def new
    @ventum = Ventum.new
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta
  # POST /venta.json
  def create
    @ventum = Ventum.new(ventum_params)

    respond_to do |format|
      if @ventum.save
        format.html { redirect_to @ventum, notice: 'Ventum was successfully created.' }
        format.json { render :show, status: :created, location: @ventum }
      else
        format.html { render :new }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1
  # PATCH/PUT /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: 'Ventum was successfully updated.' }
        format.json { render :show, status: :ok, location: @ventum }
      else
        format.html { render :edit }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1
  # DELETE /venta/1.json
  def destroy
    @ventum.destroy
    respond_to do |format|
      format.html { redirect_to venta_url, notice: 'Ventum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Ventum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventum_params
      params.require(:ventum).permit(:codigo, :cliente, :monto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SisInfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %><br>
    <%= f.text_field :cod %>
  </div>
  <div class="field">
    <%= f.label :Nombre_Producto %><br>
    <%= f.text_field :Nombre_Producto %>
  </div>
  <div class="field">
    <%= f.label :Costo %><br>
    <%= f.number_field :Costo %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos</h1>

<table>
  <thead>
    <tr>
      <th>Cod</th>
      <th>Nombre producto</th>
      <th>Costo</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.cod %></td>
        <td><%= producto.Nombre_Producto %></td>
        <td><%= producto.Costo %></td>
        <td><%= producto.stock %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cod:</strong>
  <%= @producto.cod %>
</p>

<p>
  <strong>Nombre producto:</strong>
  <%= @producto.Nombre_Producto %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @producto.Costo %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

app/views/venta/_form.html.erb
<%= form_for(@ventum) do |f| %>
  <% if @ventum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ventum.errors.count, "error") %> prohibited this ventum from being saved:</h2>

      <ul>
      <% @ventum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.number_field :monto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venta/edit.html.erb
<h1>Editing Ventum</h1>

<%= render 'form' %>

<%= link_to 'Show', @ventum %> |
<%= link_to 'Back', venta_path %>

app/views/venta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventas</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Cliente</th>
      <th>Monto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venta.each do |ventum| %>
      <tr>
        <td><%= ventum.codigo %></td>
        <td><%= ventum.cliente %></td>
        <td><%= ventum.monto %></td>
        <td><%= link_to 'Detalles', ventum %></td>
        <td><%= link_to 'Editar', edit_ventum_path(ventum) %></td>
        <td><%= link_to 'Borrar', ventum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Venta', new_ventum_path %>

app/views/venta/new.html.erb
<h1>New Ventum</h1>

<%= render 'form' %>

<%= link_to 'Back', venta_path %>

app/views/venta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @ventum.codigo %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @ventum.cliente %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @ventum.monto %>
</p>

<%= link_to 'Edit', edit_ventum_path(@ventum) %> |
<%= link_to 'Back', venta_path %>